# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cd3c7dfd7985dd3fa14e415e3cec769439a0c1b797b56345e8d88433145a86afdeed19635ac03c8463278b960d7264161263555e380a1e9844a536bfa5b1b10

test:
  secret_key_base: 35524c40bd29313d7c52163454dd7f5febf4c480b08a4d40998e9853f8849618eeb37097816051494e8a754c233e8b0e96e3f6705d2b3b958019b4cd1cda5846

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
